config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/index'
  get 'pages/home'
  root 'pins#index'

post 'pins/:id/like', as: 'pins_like', to: 'pins#like'
#rest routes
  resources :pins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :pin
end

app/models/pin.rb
class Pin < ApplicationRecord
	belongs_to :user
	has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 

devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :validatable

has_many :pins
def avatar
   type = ['men', 'women'].sample
   number = (1..99).to_a.sample
   "https://randomuser.me/api/portraits/#{type}/#{number}.jpg"
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index() end
  def home
  	#variable de instancia disponible en toda la app
  	#si no tuviera @ no llega a la vista
  	@pins = Pin.all
   end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
   
before_action :set_pin, only: [:like, :destroy, :edit, :update, :show]



   def create
	@pin = Pin.new (pin_params) #guardando instancia de pin con los parametros
	@pin.user = current_user
	if @pin.save! #guardando pin  !excclamacion para ver error
		redirect_to pins_path 
	else
		redirect new_pin_path, notice: 'Error'
	  end

  end


 def destroy
 	
 	
 	@pin.likes.delete_all
 	@pin.delete
 	redirect_to pins_path
  end

  def edit

  end

  def index
  	@pins= Pin.all
  end

 def like
 	
 	user = current_user
 	Like.create(pin: @pin, user: user)

 	redirect_to pins_path
 end

  def new
  	@pin = Pin.new
  end

  def update
  	@pin.update(pin_params)
  	redirect_to pins_path
  end

   def show


  end

 
 

  def pin_params
  	params.require(:pin).permit(:name, :desc, :photo)
  end


def set_pin
 	@pin= Pin.find(params[:id])
 	

 end

 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PinterestApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar'%>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
   
   <div class="container">
    <%= yield %>
  </div>
     

    
  </body>
 
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</html>

app/views/pages/home.html.erb
<h1>Pincheterest</h1>



  <div class="container">
 <div class="row">
   <% @pins.each do |pin| %>
     <%= render 'pins/card', pin:pin %>
   <% end %>
 </div>
</div>

app/views/pages/index.html.erb
<h1>Pincheterest</h1>

app/views/pins/_card.html.erb
<div class="col-sm">
 <div class="card" style="width: 18rem;">

 <%= link_to pin_path(pin) do %>
		<img src=<%= pin.photo %> class="card-img-top" alt="...">
	<% end %>
   <div class="card-body">
     <h5 class="card-title"> <%= pin.name %> </h5> 

     <p class="card-text"> <%= pin.desc %></p>

     <p class="card-text"> Likes: <%= pin.likes.count %></p>
     
     <% if pin.user == current_user %>
		   
	    <%=link_to 'Editar', edit_pin_path(pin), class: 'btn btn-primary' %> 
	    <%=link_to 'Borrar', pin_path(pin), method:'DELETE', class: 'btn btn-primary' %> 

    <% end %>

     <a href="/pins/<%=pin.id%>/like"
     data-method="POST"
     class="btn btn-primary">Like</a>

   </div>
 </div>
</div>

app/views/pins/edit.html.erb
<h1>Edit tu PinchePin</h1>
<%= form_with model: @pin do |f| %>

<div class='form-group'>
	<%= f.text_field :name, placeholder:'Nombre' %>
	</div>
	<div class='form-group'>
	<%= f.text_field :desc, placeholder:'Description' %>
	</div>
	<div class='form-group'>
	<%= f.text_field :photo, placeholder: 'Url photo'%>
	</div>
<div class='form-group'>
	<%= f.submit 'Crear Pin', class: 'btn btn-secondary btn-lgy' %>
	</div>

<% end %>

app/views/pins/index.html.erb
<h1>PinchePerroterest</h1>



  <div class="container">
 <div class="row">
   <% @pins.each do |pin| %>
     <%= render 'pins/card', pin:pin %>
   <% end %>
 </div>
</div>

app/views/pins/new.html.erb
<h1>Crea tu PinchePerroPin</h1>
<%= form_with model: @pin do |f| %>

<div class='form-group'>
	<%= f.text_field :name, placeholder:'Nombre' %>
	</div>
	<div class='form-group'>
	<%= f.text_field :desc, placeholder:'Description' %>
	</div>
	<div class='form-group'>
	<%= f.text_field :photo, placeholder: 'Url photo'%>
	</div>
<div class='form-group'>
	<%= f.submit 'Crear Pin', class: 'btn btn-secondary btn-lgy' %>
	</div>

<% end %>

app/views/pins/show.html.erb
<h1>Pinooooo</h1>
 
 <%= render 'pins/card', pin: @pin %> 

app/views/shared/_card.html.erb
<div class="col-sm">
 <div class="card" style="width: 18rem;">
   <img src=<%= pin.photo %> class="card-img-top" alt="...">
   <div class="card-body">
     <h5 class="card-title"> <%= pin.name %> </h5> 

     <p class="card-text"> <%= pin.desc %></p>
     <a href="#" class="btn btn-primary">Go somewhere</a>
   </div>
 </div>
</div>

app/views/shared/_form.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"">
<%= link_to pins_path do %>
  <%= image_tag asset_path('pata.gif'), class: 'img-custom' %>
 <%end %> 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item">
      <%= link_to 'Crear Pin', new_pin_path , class:'nav-link' %>
        
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

      <% if user_signed_in? %>
        <a href= "/users/sign_out" data-method="DELETE"  class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign out</a>
       <div class= "eemail"> <%= current_user.email %> </div>
      <%= image_tag current_user.avatar, class: 'img-custom img-circle'%>
       
      <% else %>
         <a href= "/users/sign_in" class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign in</a>
         <a href="/users/sign_up" class="btn btn-outline-success my-2 my-sm-0" type="submit">Sign up</a>
       <% end %>
        
    </form>
  </div>
</nav>